---
language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode
script:
  - bundle exec rake spec
after_failure: "cat /home/travis/builds/poisol/log/poisol_stub.log; cat /home/travis/builds/poisol/log/poisol_webrick.log;"
